# -*- coding: utf-8 -*-
{
    'name': 'Radhekrishn Pharma Gov Supply',
    'version': '18.0.1.0.0',
    'category': 'Purchase',
    'summary': 'Government pharma supply -- rate contracts, PO lifecycle, penalty, commission, delivery challan, dashboard',
    'author': 'Radhekrishn Biotech',
    'depends': [
        'base',
        'purchase',
        'sale_management',
        'account',
        'mail',
        'product',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/institution_data.xml',
        'data/rc_stage_data.xml',
        'data/rc_agreement_data.xml',
        'data/email_templates.xml',
        'data/ir_cron.xml',
        'views/institution_views.xml',
        'views/rc_agreement_views.xml',
        'views/purchase_order_views.xml',
        'views/dashboard_views.xml',
        'views/report_commission_invoice.xml',
        'views/report_commission_summary.xml',
        'views/report_delivery_challan.xml',
        'views/wizard_views.xml',
        'views/menu_views.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
